version: '3.1'

services:

  db:
    image: postgres
    container_name: MovieTheater
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
      - "8090:5432"